name: Auto Version Bump

on:
  push:
    branches: [main]  # altere se usar outra branch

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install toml

      - name: Commit versão
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.bump.outputs.version }}" || echo "Nada para commitar"
          git push

      - name: Criar tag
        run: |
          git tag v${{ steps.bump.outputs.version }}
          git push origin v${{ steps.bump.outputs.version }}
