name: Auto Version Bump

on:
  push:
    branches: [v2]  # altere se usar outra branch

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install toml

      - name: Incrementar versão
        id: bump
        run: |
          python3 << 'EOF'
          import toml

          file = "pyproject.toml"

          data = toml.load(file)
          version = data["project"]["version"]

          major, minor, patch = map(int, version.split("."))
          patch += 1
          new_version = f"{major}.{minor}.{patch}"

          data["project"]["version"] = new_version

          with open(file, "w") as f:
              toml.dump(data, f)

          print(f"::set-output name=version::{new_version}")
          EOF

      - name: Commit versão
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.bump.outputs.version }}" || echo "Nada para commitar"
          git push

      - name: Criar tag
        run: |
          git tag v${{ steps.bump.outputs.version }}
          git push origin v${{ steps.bump.outputs.version }}
